### PR TITLE
Switch from WebPack to Microbundle

### PR DESCRIPTION
**Pull request by hirasso**
Nothing more to add :)

- [x] The PR is submitted to the `master` branch

### CODE REVIEW

**Comment by daun** [comment]
I think entry.js can also be deleted.

**Comment by hirasso** [comment]
Ah! Overlooked that

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
@daun That would be a minor version bump, right?

**Comment by daun** [comment]
I'd suggest major to make sure we don't get any webpack/rollup compatibility problems and spare us any stress from that 🤡 Not sure if the new peer dependency requires a major anyway?

**Comment by hirasso** [comment]
> Not sure if the new peer dependency requires a major anyway?
I don't know nothing about any of that 😁

...major it is then! :)

**Pull request merged**
