### PR TITLE
Finish the animation before hiding the progress bar

### PR DESCRIPTION
**Pull request by hirasso**
Hi there! First, I must say, I LOVE YOUR LIBRARY!! :)

The progress bar felt a bit off for me, since it just hides at whatever point the page is loaded, without completing it's animation to 100% width. This PR attempts to solve that by waiting for the animation to finish before hiding the progress bar.

### CODE REVIEW

**Comment by daun** [comment]
Hi, thanks for contributing!  While I personally prefer the way it's working currently, I'm all for making it configurable. Can we make the new behaviour optional so it's not a breaking change?

**Comment by hirasso** [comment]
I agree, let's make this optional. Do you have a suggestion for an option name?

**Comment by hirasso** [comment]
Maybe a boolean `alwaysFinishTransition`?

**Comment by daun** [comment]
Mmh. I like two-word parameters. `completeTransition` sounds okay. Or maybe `hideImmediately` with a default value of `true`. What do you think?

**Comment by hirasso** [comment]
Let's go for `hideImmediately` then. I like it if default boolean options are true. OK? :)

**Comment by daun** [comment]
Perfect.

**Comment by hirasso** [comment]
I have implemented the new option: 0c84fd7fd62c7b8cbe404d347e55738b85af2848

**Comment by hirasso** [comment]
...something seems off with our editor configs. My code is indented differently then yours: https://github.com/hirasso/progress-plugin/blob/feature/optimize-animation/src/index.js

Would you care to send me an `.editorconfig`? I'm using VS Code, don't know why it didn't detect your code's indetation settings (maybe Tabs vs. Spacings? I usually use Two Spacings™️ for indentation)

**Comment by hirasso** [comment]
...ok, fixed the indentation. I changed my editor indentation settings to `Detect from Content` and re-indented all lines.

**Comment by daun** [comment]
Looks good! I'll give it a spin and merge later.

**Review by daun — APPROVED** [review]

**Comment by daun** [comment]
Thanks for contributing! I tagged a new release, not sure if it will auto-publish to npm. Let me know if it doesn't show up in the next few hours.

**Comment by hirasso** [comment]
It doesn't look like the new tag has been published to npm. I think you'll have to run something like `npm publish`, again. Also, it would be nice to be listed in the [`contributors` section](https://github.com/swup/progress-plugin/blob/master/package.json#L16-L22) in the `package.json`, if you don't mind :)

**Comment by hirasso** [comment]
If you are ok with it, I will create another pull request with my info in the `contributors` section of the `package.json`. May I?

**Comment by daun** [comment]
@hirasso Yes, please add an entry to the contributors array. While you're at it, can you submit the PR with the version in package.json bumped to `1.1.1`? The repo's permissions are mangled, I can approve and merge PRs but I can't submit and merge my own apprently 🤡 Will do some restructuring here, but in the meantime you can bump the version and I'll tag the release. The reason it didn't publish last time was that I didn't bump the version.

**Pull request merged**
