### PR TITLE
feat: animate scale instead of width

### PR DESCRIPTION
**Pull request by hirasso**
**Description**

I just needed a way to adjust the width of the progress bar in a project to a value lower than 100%. That wasn't possible because the plugin was always animating the `width` to `100%`.

**Solution**

Animate the `scale` instead, from `0` to `1`. I tried to be as defensive as possible in the implementation, preserving the `translate3d(0, 0, 0)` that was present in the code intact. I don't think it's necessary, but also don't want to create any issues with rendering that I remember we had once upon a time with the plugin.

**Drive-By**

- Added `aria-hidden="true"` to the progress bar element

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)

### CODE REVIEW

**Comment by daun** [comment]
There some whitespace glitch again, it seems — time for another editorconfig file 🤠

Screenshot 2024-04-04 at 23 25 54

**Comment by daun** [comment]
How about updating a custom property to make it 100% customizable? They [more than match](https://caniuse.com/css-variables) our support matrix, and we made the switch in the themes as well I think?

```css
/* in the base css */
.progress-bar {
  transform: translate3d(0, 0, 0) scaleX(var(--value, 0));
}
```

```js
refresh() {
  this.progressElement.style.setProperty("--value", this.value);
}
```

**Comment by hirasso** [comment]
What's the use case you have in mind for using a custom property here?

**Comment by hirasso** [comment]
How could one use `--value` to customize it?

**Comment by daun** [comment]
I had a use case recently where the progress bar was a diagonal gradient. I created a custom plugin for that, but it wouldn't be necessary if I could just do:

```css
.swup-progress-bar {
  transform: none !important; /* reset default style */
  background: linear-gradient(
    to bottom right,
    black calc(100% * var(--value, 0)),
    white calc(100% * var(--value, 0))
  );
}
```

**Comment by hirasso** [comment]
interesting. Ok! Lets do it

**Comment by hirasso** [comment]
Should we call the variable `--value`? or `--progress`?

**Comment by daun** [comment]
`--progress` is much better 🧃

**Comment by hirasso** [comment]
:) ok

...I just noticed that the progress element is currently inserted _before_ the `<body>`: 

```js
document.documentElement.insertBefore(this.progressElement!, document.body);
```

Is there a reason it is like that? Otherwise I would probably prepend it to the `<body>` instead.

**Comment by daun** [comment]
There's an old issue about that somewhere. It caused some problems trying to change it in the past, but I don't quite remember. Best not touch it until we know better 🤡

**Comment by hirasso** [comment]
Ready for review – tested it in my current project, works fine :)

**Comment by daun** [comment]
Hehe. There's literally only [one issue on this repo](https://github.com/swup/progress-plugin/issues/1) and it was about that 🤠 Turns out the problem was something else. But best focus on one thing at a time, unless you're very motivated...

**Review by daun — DISMISSED** [review]
🚤

**Comment by hirasso** [comment]
From that issue: 

> As for the div outside of body, I think it would be better to place it right at the top of body, but nowadays browser takes whatever you give it, so I guess it doesn't matter.

I strongly agree! I'll prepend it to the body. I'll also make sure to help out should we get bug reports for this (I doubt it).

**Comment by hirasso** [comment]
Changes in last commit:

- Prepend the progress element to the `<body>`
- The style element was being inserted _every time_ in `show()`. Changed that so that the style is only being inserted once. 
- Some unnecessary TS `!` after values

Is that too much for one PR? I never can get enough 😋😋

It's still working nicely in my test project.

**Comment by daun** [comment]
The style tag is re-inserted every time since some users use the head plugin without persisting assets, which would remove it from the head after the first navigation. Probably need to reverse that one unless I'm confusing things :)

**Comment by hirasso** [comment]
@daun ✅

**Comment by hirasso** [comment]
Although after checking https://swup.js.org/plugins/head-plugin/#persistassets, `persistAssets` seems to be `false` by default and it was still working for me. Would also have to be broken if the style tag was actually being removed during a visit – the progress bar would loose all it's styles on `content:replace`.

But better to be sure, who knows what else could have happened to the head after the last visit.

**Comment by daun** [comment]
Might be that the style tag ends up in the body? In which case the head plugin wouldn't touch it. Complicated stuff 😭

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
No it ends up in the head. Anyways. It works 🤷‍♂️

**Pull request merged**
